### ISSUE TITLE
Action output

### ISSUE THREAD

**Issue by danielMCF99** [OrchidIsle/UE5-Build-Project#10]
Is it part of the roadmap to develop the action to return a zip file with the result of the packaging process as an output?

**Comment by edwardteach42** [comment]
I think that would more be part of your engine packaging process. We currently handle the zip process using tar, which comes packaged with windows 10 and 11 as the step following this action running. Powershell Compress-Archive command has a hard 2Gb limit while tar does not. Here is the step that we use in our build process

```
- name: Compress Win64 Client
  run: tar -czvf MyGame-Win64-${{ env.BUILD_ID }}.tar.gz -C ${{ github.workspace }}\MyGame\Saved\StagedBuilds\Windows .
```

**Comment by edwardteach42** [comment]
We do have plans to create a tutorial series showing how to set up an unreal project for continuous integration using all of our marketplace actions. We are currently working on a separate marketplace action that will create patch files for games.
